version: '3.8'

services:
  aptcacher:
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
    image: "gnzsnz/apt-cacher-ng:latest"
    container_name: aptcacher
    hostname: aptcacher
    environment:
      ACNG_TRUNC: '$ACNG_TRUNC'
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
        compress: "true"
    ports:
        - "3142:3142"
    volumes:
        - aptcacher-cache:/var/cache/apt-cacher-ng

volumes:
    aptcacher-cache:
      name: aptcacher-cache
