version: '3.5'

services:
    aptcacher:
        image: "gnzsnz/apt-cacher-ng:202011"
        container_name: aptcacher
        hostname: aptcacher
        restart: always
        ports:
            - "3142:3142"
        volumes:
            - aptcacher-cache:/var/cache/apt-cacher-ng

volumes:
    aptcacher-cache:
      name: aptcacher-cache
      external: true      
