version: '3.8'

services:
  aptcacher:
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
    image: "gnzsnz/apt-cacher-ng:202209"
    container_name: aptcacher
    hostname: aptcacher
    environment:
      ACNG_TRUNC: ${ACNG_TRUNC}
    restart: "unless-stopped"
    ports:
        - "3142:3142"
    volumes:
        - aptcacher-cache:/var/cache/apt-cacher-ng

volumes:
    aptcacher-cache:
      name: aptcacher-cache
