name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get enviroment variables
      run: |
        grep -v '#' .env-dist | grep '=' > .env
        while IFS= read -r line; do 
          echo $line >> $GITHUB_ENV ; 
        done < .env
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile \
        --build-arg UID=${{ env.UID }}  --build-arg GID=${{ env.GID }} \
        --tag ${{ github.repository }}:${{ env.IMAGE_VERSION }}

    - name: Run container
      run: |
        docker run -p 3142:3142 \
        ${{ github.repository }}:${{ env.IMAGE_VERSION }} aptcacher

    - name: Set-up runner APT
      run: |
        sudo rm -rf /var/lib/apt/lists/*
        echo 'Acquire::http { Proxy "http://127.0.0.1:3142"; }' | tee /etc/apt/apt.conf.d/01proxy
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

    - name: aptcacher container log verification
      run: |
        eval export $(grep DISTRIB_CODENAME lsb-release)
        docker logs -t aptcacher | grep $DISTRIB_CODENAME
