name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get enviroment variables
      run: while IFS= read -r line; do echo $line >> $GITHUB_ENV ; done < $(grep -v '#' .env-dist)
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile \
            --build-arg UID=${{ env.UID }}  --build-arg GID=${{ env.GID }} \
            --tag $GITHUB_REPOSITORY:${{ env.IMAGE_VERSION }}
