name: apt-cacher-ng Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and test aptcacher
    strategy:
      matrix:
        image_os: [focal, jammy]
        runner_os: [20.04, 22.04]

    runs-on: ubuntu-${{ matrix.runner_os}}
    continue-on-error: true

    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get enviroment variables
        run: |
          grep -v '#' .env-dist | grep '=' > .env
          while IFS= read -r line; do 
            echo $line >> $GITHUB_ENV ; 
          done < .env
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build apt-cacher Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          context: .
          build-args: |
            BASE_VERSION=${{ env.BASE_VERSION }}
            IMAGE_VERSION=${{ env.IMAGE_VERSION }}
            UID=${{ env.UID }}
            GID=${{ env.GID }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-${{ matrix.image_os }}

      - name: Run container
        run: |
          docker run -d -p 3142:3142 \
          --name aptcacher \
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-${{ matrix.image_os }}

      - name: Set-up runner APT proxy
        run: |
          sudo rm -rf /var/lib/apt/lists/*
          echo 'Acquire::http { Proxy "http://127.0.0.1:3142"; }' | \
          sudo tee /etc/apt/apt.conf.d/01proxy
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

      - name: aptcacher container log verification
        run: |
          eval export $(grep DISTRIB_CODENAME /etc/lsb-release)
          docker logs -t aptcacher | grep $DISTRIB_CODENAME && exit 0 || exit 1
